# railway.yml

version: '1.0'
services:
  app:
    image: "e-weather"
    env:
      - DATABASE_URL=${RAILWAY_POSTGRESQL_URL}
    buildCommand: go build -o ./bin/main .
    runCommand: ./bin/main
    envFile: .env
  database:
    image: "postgres"
    env:
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_DB=e-weather
